### String Manipulation

__Exercise1:__ Write a Python program to get a string made of the first 2 and the last 2 chars from a given a string. If the string length is less than 2, return instead of the empty string.
```
Sample String : 'w3resource'
Expected Result : 'w3ce'
Sample String : 'w3'
Expected Result : 'w3w3'
Sample String : ' w'
Expected Result : Empty String 
```


In [ ]:
def string_both_ends(str):
  if len(str) < 2:
    return ''

  return str[0:2] + str[-2:]

print(string_both_ends('w3resource'))
print(string_both_ends('w3'))
print(string_both_ends('w'))


__Exercise 2__ Write apython program to count repeated characters in a string. Go to the editor

Sample string: 'thequickbrownfoxjumpsoverthelazydog'
```
Expected output :
o 4
e 3
u 2
h 2
r 2
t 2
```

In [2]:
import collections
str1 = 'thequickbrownfoxjumpsoverthelazydog'
d = collections.defaultdict(int)
for c in str1:
    d[c] += 1

for c in sorted(d, key=d.get, reverse=True):
  if d[c] > 1:
      print('%s %d' % (c, d[c]))


o 4
e 3
r 2
u 2
h 2
t 2


### List
__Exercise 3__ Write a Python program to print a specified list after removing the 0th, 4th and 5th elements. 

Sample List : ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']

Expected Output : ['Green', 'White', 'Black']

In [3]:
color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
color = [x for (i,x) in enumerate(color) if i not in (0,4,5)]
print(color)


['Green', 'White', 'Black']


## Dictionary

__Exercise 4:__ Write a Python program to remove duplicates from Dictionary

In [6]:
student_data = {'id1': 'ABC', 'id2': 'XYZ', 'id1': 'ABC', 'id2': 'XYZ'}
result= {}
for key,value in student_data.items():
    if value not in result.values():
        result[key] = value

print(result)


{'id2': 'XYZ', 'id1': 'ABC'}


__Exercise 5:__ Write a Python program to sort Counter by value

Sample data : {'Math':81, 'Physics':83, 'Chemistry':87}

Expected data: [('Chemistry', 87), ('Physics', 83), ('Math', 81)]


In [8]:
from collections import Counter
x = Counter({'Math':81, 'Physics':83, 'Chemistry':87})
print(x.most_common())


[('Chemistry', 87), ('Physics', 83), ('Math', 81)]


### Numpy

__Exercise 6:__ Write a Python program to create a 5x5 array with random values and find the minimum and maximum values.



In [9]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.84286678 0.14414808 0.47478746 0.8528399  0.01238245]
 [0.61401283 0.26056858 0.01460317 0.44510548 0.01956929]
 [0.86892856 0.14385521 0.66846263 0.00108633 0.99102811]
 [0.47354004 0.27107481 0.92986688 0.90929627 0.0631555 ]
 [0.20856599 0.94430371 0.51616735 0.98155299 0.47198487]]
Minimum and Maximum Values:
0.0010863328585809517 0.9910281077468985


__Exercise 7:__ Write a Python program to find the most frequent value in an array.


In [10]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[7 1 7 9 1 0 9 3 5 2 9 8 5 3 0 5 3 5 3 4 5 0 5 8 2 1 1 9 1 5 9 5 4 3 8 1 3
 2 4 0]
Most frequent value in the above array:
5


__Exercise 8:__ Write a Python program to find point by point distances of a random vector with shape (10,2) representing coordinates.


In [14]:
import numpy as np
a= np.random.random((3,2))
print("A: ", a)
x,y = np.atleast_2d(a[:,0], a[:,1])
print("X:", x)
print("Y:", y)
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)


A:  [[0.14376826 0.40787055]
 [0.84834475 0.73079595]
 [0.37605351 0.35198025]]
X: [[0.14376826 0.84834475 0.37605351]]
Y: [[0.40787055 0.73079595 0.35198025]]
[[0.         0.77505408 0.23891455]
 [0.77505408 0.         0.60544227]
 [0.23891455 0.60544227 0.        ]]
