# Q-Table Learning

In [2]:
import gym
import numpy as np

ModuleNotFoundError: No module named 'gym'

### Load the environment

In [4]:
env = gym.make('FrozenLake-v0')

# FrozenLake

## The agent controls the movement of a character in a grid world. Some tiles of the grid are walkable, and others lead to the agent falling into the water.

The surface is described using a grid like the following:

SFFF       (S: starting point, safe)
FHFH       (F: frozen surface, safe)
FFFH       (H: hole, fall to your doom)
HFFG       (G: goal, where the frisbee is located)




In [5]:
env.render()


SFFF
FHFH
FFFH
HFFG



The episode ends when you reach the goal or fall in a hole. You receive a reward of 1 if you reach the goal, and zero otherwise.


### Implement Q-Table learning algorithm

# Q table - Knowledge or Learning

In this we will be maintaing the Q-Table which is the actual Knowledge we will have of which direction to move into

Total Tiles: 16
possible Action at each state: 4

We will maintain our knowledge as 16X4 with probability of likelihood of how which action is preferable at each step.

Initial at start we don't have any knowledge. Initialize all 16X4 with zeros.

https://gym.openai.com/envs/FrozenLake-v0/

In [6]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Reinforced Learning Main Ideas:

At each step we use our acquired knowledge from Q-Table. 

But we also add a element of randomness in our greedy approach to learn about the environment.


In [8]:
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        # Chooses an action by using our knowledge from Q table and 
        # using some random values generated using Random function from numpy
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        if i == 356 and True:
            print("Step", j )
            env.render()
        s = s1
        if d == True:
            break
    if False:
        print("Episode : " , i)
        env.render()
    #jList.append(j)
    rList.append(rAll)

Step 1
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 2
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 3
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 4
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 5
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 6
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 7
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 8
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 9
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 10
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 11
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 12
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 13
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 14
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 15
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 16
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 17
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 18
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 19
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 20
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 21
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 22
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 23
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 24
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 25
  (Up)
SFFF
FHFH
FFFH
HFFG
Step 26
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 27
  (Right)
SFFF
FHFH
FFFH
HFFG
Step 28
  (Right)
SFFF
FHFH
FFFH
H

In [9]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.912


# Observe Q-Table to see if we learn about the environment

SFFF
FHFH
FFFH
HFFG


In [10]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[6.30708261e-02 3.77854159e-03 3.68420064e-03 3.75990683e-03]
 [1.03753651e-04 4.56903283e-04 6.39414990e-04 1.03923300e-01]
 [8.21154664e-04 7.78218873e-04 9.79940656e-04 1.40741587e-01]
 [6.00887652e-04 1.35079419e-04 1.40189587e-04 9.03500050e-02]
 [2.08112108e-01 1.61060099e-03 3.61884388e-03 9.53895110e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.74315297e-04 4.68596343e-10 3.37946845e-02 5.09064758e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.34246852e-03 2.43906654e-03 3.30100380e-03 1.67965854e-01]
 [1.60841574e-03 1.03478219e-01 1.23298615e-03 8.18822740e-04]
 [2.54282403e-01 0.00000000e+00 1.22042586e-03 9.69696333e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.84249597e-01 2.68883408e-03]
 [0.00000000e+00 0.00000000e+00 6.09799550e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.